# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='orgImages/%Y/%m/%d')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
