# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0004_auto_20180508_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='imgType',
            field=models.CharField(default='ImageTarget', max_length=25),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='meta',
            field=models.FileField(blank=True, upload_to='metaDocuments/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='size',
            field=models.CharField(default='150', max_length=15),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='targetID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='orgImages/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='name',
            field=models.CharField(default='testImage', max_length=150),
            preserve_default=False,
        ),
    ]
