# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0005_auto_20180514_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='status',
            field=models.CharField(blank=True, default='1', max_length=15),
        ),
    ]
