# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0009_auto_20180515_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='video_URL',
            field=models.CharField(blank=True, max_length=950, null=True),
        ),
    ]
