# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0012_auto_20180605_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='fullScreen',
            field=models.BooleanField(default=False),
        ),
    ]
